[counter]
# Must match the docker compose file
hostname = "counter"
port = "8080"

[agent]
enable_encryption = false
enable_script_checks = true
datacenter = "dc1"
log_level = "INFO"
# Must match the docker compose file
retry_join = ["consul-server-bootstrap"]
server = false
ui = false


[ports]
dns = 8600
http = 8500
https = -1
serf_lan = 8301
serf_wan = 8302
server = 8300

[encryption]
gossip = false
#gossip_key = false
#verify_gossip_incoming = false
#verify_gossip_outgoing = false
tls = false
#verify_incoming = false
#verify_outgoing = false
#verify_server_hostname = false
#ca_file = ""
#cert_file = ""
#key_file = ""