[agent]
client_addr = "0.0.0.0"
enable_script_checks = true
datacenter = "dc1"
log_level = "INFO"
# Must match the docker compose file
retry_join = "consul-server"
server = false
ui = false

[ports]
dns = 8600
http = 8500
grpc = 8502
https = -1
serf_lan = 8301
serf_wan = 8302
server = 8300

[counter-connect]
hostname = "localhost"
listen_port = 18080
port = 8080
protocol = "http"

[consul]
hostname = "localhost"
# TODO: This IP address is currently hard coded for dnsmasq, it should be refactored to use consul-template
ip = "172.20.0.10"
port = 8500
protocol = "http"
