#!/bin/sh

set -eox

{{pkgPathFor "errygg/dnsmasq"}}/bin/dnsmasq -x $svc_path/dnsmasq.pid -C {{pkg.svc_config_path}}/dnsmasq.conf 2>&1

exec 2>&1
export COUNTING_SERVICE_URL={{{cfg.counter.protocol}}}://{{cfg.counter.hostname}}:{{cfg.counter.port}}
export PORT={{cfg.dashboard.port}}
exec {{pkg.path}}/bin/dashboard
