#!{{pkgPathFor "core/bash"}}/bin/bash

set -eox

exec 2>&1

export COUNTING_SERVICE_URL={{{cfg.counter.protocol}}}://{{cfg.counter.hostname}}:{{cfg.counter.port}}
export PORT={{cfg.dashboard.port}}

exec {{pkg.path}}/bin/dashboard
