#!{{pkgPathFor "core/bash"}}/bin/bash

set -eox

exec 2>&1

# Wait until the consul agent is up
until $(curl --output /dev/null --silent --head --fail {{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}}); do
  sleep 1
done

# Register service with consul
{{pkgPathFor "core/curl"}}/bin/curl \
  --request PUT \
  --data @/hab/svc/counter-connect/config/counter-connect.json \
  {{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}}/v1/agent/service/register

# Enable the service for connect
exec {{pkgPathFor "errygg/consul"}}/bin/consul connect proxy \
  -http-addr={{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}} \
  -service=counter-connect \
  -service-addr=127.0.0.1:{{cfg.counter-connect.port}} \
  -listen={{sys.ip}}:{{cfg.counter-connect.listen_port}} \
  -register
  