#!/bin/sh

set -eox

exec 2>&1

# Register service with consul
exec {{pkgPathFor "core/curl"}}/bin/curl \
  --request PUT \
  --data @/hab/svc/counter/config/counter.json \
  {{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}}/v1/agent/service/register
  