[counter]
hostname = "counter"
port = 8080
protocol = "http"

[consul]
hostname = "consul-client-counter.node.consul"
# TODO: This IP address is currently hard coded for dnsmasq, it should be refactored to use consul-template
ip = "172.20.0.10"
port = 8500
protocol = "http"
