#!{{pkgPathFor "core/bash"}}/bin/bash

set -eox

exec 2>&1

# Wait until the consul agent is up
until $(curl --output /dev/null --silent --head --fail {{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}}); do
  sleep 1
done

# Register service with consul
{{pkgPathFor "core/curl"}}/bin/curl \
  --request PUT \
  --data @/hab/svc/dashboard-connect/config/dashboard-connect.json \
  {{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}}/v1/agent/service/register

exec {{pkgPathFor "errygg/consul"}}/bin/consul connect proxy \
  -http-addr={{cfg.consul.protocol}}://{{cfg.consul.hostname}}:{{cfg.consul.port}} \
  -service=dashboard-connect \
  -upstream="counter-connect:8080"
  