#!/bin/sh

set -eox

exec 2>&1

{{pkgPathFor "errygg/consul"}}/bin/consul agent -config-file={{pkg.svc_config_path}}/agent.hcl & 2>&1
{{pkgPathFor "errygg/dnsmasq"}}/bin/dnsmasq -x $svc_path/dnsmasq.pid -C {{pkg.svc_config_path}}/dnsmasq.conf 2>&1

export COUNTING_SERVICE_URL={{{cfg.counter-connect.protocol}}}://{{cfg.counter-connect.hostname}}:{{cfg.counter-connect.port}}
export PORT={{cfg.dashboard-connect.port}}
exec {{pkg.path}}/bin/dashboard-connect
